[config]

[templates.hyprland]
input_path = '/home/marc/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/marc/.config/hypr/matugen.conf'
post_hook = "lua /home/marc/linux-config/scripts/reload-hyprland-theme.lua"

[templates.noctalia]
input_path = "/home/marc/.config/matugen/templates/noctalia.json"
output_path = "/home/marc/.config/noctalia/colors.json"

[templates.alacritty]
input_path = "/home/marc/.config/matugen/templates/alacritty.toml"
output_path = "/home/marc/.config/alacritty/themes/theme.toml"

[templates.nvim]
input_path = "/home/marc/.config/matugen/templates/nvim.lua"
output_path = "/home/marc/.config/nvim/colorschemes/intellij.nvim/lua/intellij/matugen.lua"
post_hook = "sh /home/marc/linux-config/scripts/reload-nvim-colorscheme.sh"
#
# [templates.eww]
# input_path = "~/.config/matugen/templates/eww.scss"
# output_path = "~/.config/eww/colors.scss"

[templates.waybar]
input_path = '/home/marc/.config/matugen/templates/colors.css'
output_path = '/home/marc/.config/waybar/colors.css'

# [templates.rofi]
# input_path = '~/.config/matugen/templates/rofi-colors.rasi'
# output_path = '~/.config/rofi/colors.rasi'
#
[templates.gtk3]
input_path = '/home/marc/.config/matugen/templates/gtk-colors.css'
output_path = '/home/marc/.config/gtk-3.0/gtk.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '/home/marc/.config/matugen/templates/gtk-colors.css'
output_path = '/home/marc/.config/gtk-4.0/gtk.css'

[templates.pywalfox]
input_path = '/home/marc/.config/matugen/templates/firefox.json'
output_path = '/home/marc/.cache/wal/colors.json'
post_hook = "pywalfox update"

[templates.wlogout]
input_path = '/home/marc/.config/matugen/templates/colors.css'
output_path = '/home/marc/.config/wlogout/colors.css'

[templates.swaync]
input_path = '/home/marc/.config/matugen/templates/colors.css'
output_path = '/home/marc/.config/swaync/colors.css'
post_hookk = "swaync-client -rs"

[templates.walker]
input_path = '/home/marc/.config/matugen/templates/colors.css'
output_path = '/home/marc/.config/walker/colors.css'

[templates.ags]
input_path = '/home/marc/.config/matugen/templates/colors.css'
output_path = '/home/marc/.config/ags/colors.scss'
#
# [templates.sequences]
# input_path = '~/.config/matugen/templates/sequences'
# output_path = '~/.cache/wal/sequences'
#
# [templates.primary]
# input_path = '~/.config/matugen/templates/primary'
# output_path = '~/.config/ml4w/colors/primary'
#
# [templates.secondary]
# input_path = '~/.config/matugen/templates/secondary'
# output_path = '~/.config/ml4w/colors/secondary'
#
# [templates.on_surface]
# input_path = '~/.config/matugen/templates/onsurface'
# output_path = '~/.config/ml4w/colors/onsurface'
#
# [templates.ohmyposh]
# input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
# output_path = '~/.config/ohmyposh/colors.json'
# post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"
