gui:
  nerdFontsVersion: 3
  showFileIcons: true
keybinding:
  universal:
    goInto: l
    prevBlock: <c-k>
    nextBlock: <c-j>
    prevBlock-alt: <disabled>
    nextBlock-alt: <disabled>
  commits:
    moveDownCommit: <disabled>
    moveUpCommit: <disabled>
