
$background = rgb(151217)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(332f35)

$inverse_primary = rgb(715289)

$inverse_surface = rgb(e8e0e8)

$on_background = rgb(e8e0e8)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(402357)

$on_primary_container = rgb(f2daff)

$on_primary_fixed = rgb(2a0c41)

$on_primary_fixed_variant = rgb(583a6f)

$on_secondary = rgb(372c3f)

$on_secondary_container = rgb(eeddf5)

$on_secondary_fixed = rgb(221829)

$on_secondary_fixed_variant = rgb(4e4256)

$on_surface = rgb(e8e0e8)

$on_surface_variant = rgb(cdc3ce)

$on_tertiary = rgb(4c2529)

$on_tertiary_container = rgb(ffdadb)

$on_tertiary_fixed = rgb(321015)

$on_tertiary_fixed_variant = rgb(663a3f)

$outline = rgb(968e98)

$outline_variant = rgb(4b454d)

$primary = rgb(ddb9f7)

$primary_container = rgb(583a6f)

$primary_fixed = rgb(f2daff)

$primary_fixed_dim = rgb(ddb9f7)

$scrim = rgb(000000)

$secondary = rgb(d1c1d9)

$secondary_container = rgb(4e4256)

$secondary_fixed = rgb(eeddf5)

$secondary_fixed_dim = rgb(d1c1d9)

$shadow = rgb(000000)

$source_color = rgb(6d15ab)

$surface = rgb(151217)

$surface_bright = rgb(3c383e)

$surface_container = rgb(221e24)

$surface_container_high = rgb(2d292e)

$surface_container_highest = rgb(383339)

$surface_container_low = rgb(1e1a20)

$surface_container_lowest = rgb(100d12)

$surface_dim = rgb(151217)

$surface_tint = rgb(ddb9f7)

$surface_variant = rgb(4b454d)

$tertiary = rgb(f4b7bb)

$tertiary_container = rgb(663a3f)

$tertiary_fixed = rgb(ffdadb)

$tertiary_fixed_dim = rgb(f4b7bb)

