require("monitors")
require("conf/keyboard")
require("conf/autostart")
require("conf/window")
require("conf/decoration")
require("conf/layout")
-- require("workspaces")
require("conf/misc")
require("keybinds")
require("conf/windowrule")
require("conf/animation")
hl.dsp.exec_cmd("/home/marc/Software/awww/target/release/awww-daemon")
-- require("ml4w")
-- require("conf/custom")
