-- Generated by nwg-displays on 2026-08-14 at 14:05:55. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120.0",
    position = "2242x1440",
    scale = 1.5
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "0x173",
    scale = 1.0
})
hl.monitor({
    output = "DP-11",
    mode = "2560x1440@59.95",
    position = "4480x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-12",
    mode = "2560x1440@59.95",
    position = "1920x0",
    scale = 1.0
})
