hl.workspace_rule({ workspace="1", monitor = "DP-2", default = true })
hl.workspace_rule({ workspace="2", monitor = "DP-3", default = true })
hl.workspace_rule({ workspace="3", monitor = "DP-1", default = true })
hl.workspace_rule({ workspace="4", monitor = "HDMI-A-2", default = true })
hl.workspace_rule({ workspace="5", monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace="6", monitor = "DP-2" })
hl.workspace_rule({ workspace="7", monitor = "DP-3" })
hl.workspace_rule({ workspace="8", monitor = "DP-1" })
hl.workspace_rule({ workspace="9", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="10", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="11", monitor = "DP-2" })
hl.workspace_rule({ workspace="12", monitor = "DP-3" })
hl.workspace_rule({ workspace="13", monitor = "DP-1" })
hl.workspace_rule({ workspace="14", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="15", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="16", monitor = "DP-2" })
hl.workspace_rule({ workspace="17", monitor = "DP-3" })
hl.workspace_rule({ workspace="18", monitor = "DP-1" })
hl.workspace_rule({ workspace="19", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="20", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="21", monitor = "DP-2" })
hl.workspace_rule({ workspace="22", monitor = "DP-3" })
hl.workspace_rule({ workspace="23", monitor = "DP-1" })
hl.workspace_rule({ workspace="24", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="25", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="26", monitor = "DP-2" })
hl.workspace_rule({ workspace="27", monitor = "DP-3" })
hl.workspace_rule({ workspace="28", monitor = "DP-1" })
hl.workspace_rule({ workspace="29", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="30", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="31", monitor = "DP-2" })
hl.workspace_rule({ workspace="32", monitor = "DP-3" })
hl.workspace_rule({ workspace="33", monitor = "DP-1" })
hl.workspace_rule({ workspace="34", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="35", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="36", monitor = "DP-2" })
hl.workspace_rule({ workspace="37", monitor = "DP-3" })
hl.workspace_rule({ workspace="38", monitor = "DP-1" })
hl.workspace_rule({ workspace="39", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="40", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="41", monitor = "DP-2" })
hl.workspace_rule({ workspace="42", monitor = "DP-3" })
hl.workspace_rule({ workspace="43", monitor = "DP-1" })
hl.workspace_rule({ workspace="44", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="45", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace="46", monitor = "DP-2" })
hl.workspace_rule({ workspace="47", monitor = "DP-3" })
hl.workspace_rule({ workspace="48", monitor = "DP-1" })
hl.workspace_rule({ workspace="49", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace="50", monitor = "HDMI-A-1" })
