hl.on("hyprland.start", function()
	-- xdg-desktop-portal-hyprland (screen capture)
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("~/.config/ml4w/listeners.sh --startall")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("swaync")
	hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("~/.config/ml4w/scripts/ml4w-autostart.sh")
	hl.exec_cmd("~/.config/hypr/scripts/cleanup.sh")
	hl.exec_cmd("~/.config/hypr/scripts/wallpaper-restore.sh")
	hl.exec_cmd("/home/marc/Software/awww/target/release/awww-daemon")
	hl.exec_cmd("qs -c noctalia-shell")
end)
